name: manage-azure-policy-3c1852df
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/RDP_access_from_the_Internet_should_be_blocked_e372f825-a257-4fb8-9175-797a8a8627d6/**'
#      - .github/workflows/manage-azure-policy-3c1852df.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_3c1852df}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/RDP_access_from_the_Internet_should_be_blocked_e372f825-a257-4fb8-9175-797a8a8627d6/**
